[package]
name = "wasmtime-example"
version = "0.1.0"
authors = ["PureStake"]
edition = "2018"

[dependencies]
anyhow = "1.0"
wasmtime = { version = "0.30.0", default-features = false, features = [
    "cache",
    "cranelift",
    "jitdump",
    "parallel-compilation",
] }

